services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cadeirasdentistas-api
    ports:
      - "5043:5043" # Porta debug
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:5042;http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Port=3306;Database=CadeirasDentistas;User=user;Password=password;
    depends_on:
      - mysql
    restart: always


  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Admin123$
      MYSQL_DATABASE: CadeirasDentistas
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always